import Head from "next/head";
import Link from "next/link";
import { Typography } from "@mui/material";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href={"/mqtt"}>
                <Typography variant="h1">To MQTT</Typography>
            </Link>
        </>
    );
}
